# Generated by Django 2.1.2 on 2019-01-14 03:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20190113_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='')),
                ('text', models.TextField(verbose_name='本文')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qa.Day', verbose_name='紐づく記事')),
            ],
        ),
    ]
