# Generated by Django 2.1.2 on 2019-01-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='名前'),
        ),
    ]
